version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: always
    container_name: postgres_user_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"