"""update news table

Revision ID: 07f1d5e8d085
Revises: c770c8fd1482
Create Date: 2025-03-25 14:57:58.990402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f1d5e8d085'
down_revision: Union[str, None] = 'c770c8fd1482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('endpoint_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('news', sa.Column('author', sa.String(), nullable=True))
    op.add_column('news', sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'published_at')
    op.drop_column('news', 'author')
    op.drop_column('news', 'identifier')
    op.drop_column('news', 'endpoint_id')
    # ### end Alembic commands ###
